name: Update Benchmark Data

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run benchmark updater
        run: python update_benchmark.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add freelance_rate_benchmarks_combined.json
          git commit -m "Auto-update benchmark data"
          git push
